### PR TITLE
fixes for eap7/wildfly10:

### PR DESCRIPTION
**Pull request by sfri**
- java8
- resteasy 3.0
- jackson 2.8.8
- fix weld warning on startup

### CODE REVIEW

**Comment by mp911de** [comment]
Thanks for your pull request. Would you mind splitting the single commit into two commits:

1. Dependency upgrades
2. The Java-8 related changes

**Comment by sfri** [comment]
Sure thing. Working on it.

**Comment by mp911de** [comment]
This PR has merge conflicts after merging #2. As soon as these are resolved, I'd merge the dependency upgrades.

**Comment by mp911de** [comment]
Thanks. That's merged via 5720639.

**Pull request closed without merging**
